#!/usr/bin/env bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

script_dir="$( cd "$(dirname "$0")" ; pwd -P )"
source_dir=$(realpath "$script_dir/../")/
deploy_dir="~/worktree/HumanSwitching.jl"
